# Generated by Django 3.2.6 on 2021-08-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_favorited',
            new_name='is_favorite',
        ),
    ]
